export const siteConfig = {
  name: "Abdulmajeed Abdullateef - Applied AI Engineer",
  authorName: "Abdulmajeed Abdullateef",
  username: "abdulmajeedabdullateef",
  description:
    "AbdulMajeed AbdulLateef - Applied AI Engineer working at the intersection of AI, data, and scalable software systems. Explore my projects, experience, and contributions in software development and AI.",
  url: "https://abdulmajeedabdullateef.xyz",
  links: {
    twitter: "https://x.com/Abdulma51010322", 
    github: "https://github.com/Abdulmajeed82",
    templateRepo: "https://github.com/abdulmajeedabdullateef/minimal-next-portfolio",
  },
  ogImage:
    "https://res.cloudinary.com/dvt5vkfwz/image/upload/v1767384721/Abdulmajeed portfolio_og_image.png",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/Abdulmajeed-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/Abdulmajeed-logo.png",
  keywords: [
    "Abdulmajeed Abdullateef",
    "Applied AI Engineer",
    "AI-Augmented Software Engineer",
    "Full Stack Developer",
    "Web3 Developer",
    "Solidity Specialist",
    "Next.js Developer",
    "React Developer",
    "TypeScript",
    "Kilo Code Expert",
    "GitHub Copilot Workflow",
    "Technical Operations",
    "Blockchain Engineering",
    "Kaduna Tech Talent",
    "Software Development Nigeria",
    "Handyman Marketplace Developer",
    "AI Integration Specialist",
    "Scalable Software Systems",
    "Data-Driven Applications",
    "AI-Powered Solutions",
    "AI-Enhanced User Experiences",
    "AI-Driven Development",
    "AI and Software Synergy",
    "AI in Full Stack Development", 
    "AI for Web3 Applications",
    "AI in Blockchain Solutions",
    "AI in Technical Operations",
    "AI Startup Enthusiast",
  ],
};
